# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0Th-B3800D3FSoCMBlkk8PmKf_gWShD
"""

def getBowVec(item, w2i):
  vec = np.zeros(num_words)
  for word in item:
      vec[w2i[word]] +=1
  return vec


class bowDataset(Dataset):
    def __init__(self, x, y, w2i):
        super().__init__()
        self._x = x
        self._y = y
        self.w2i = w2i
        
    def __len__(self):
        return len(self._x)
      
    def __getitem__(self, index):
        x_item = getXitem(self._x[index], self.w2i)
        y_item = classes.index(self._y[index])
        return torch.FloatTensor(x_item), torch.LongTensor([y_item])


class BOW(nn.Module):
    def __init__(self):
        super(BOW, self).__init__()
        self.linear = nn.Linear(num_words, num_classes)


    def forward(self, inp):
        x = self.linear(inp)
        return x